### ISSUE TITLE
License Mismatch

### ISSUE THREAD

**Issue by knpwrs** [arkenthera/electron-vibrancy#1]
`package.json` specifies the license as `MIT` but all of the source files contain a `GPL` header. The `LICENSE` file appears to be `MIT`. Is this supposed to be dual licensed? Pure `MIT`? Pure `GPL`?

**Comment by arkenthera** [comment]
Sorry about this. I copy pasted the license text from other projects. This project is under ```MIT```.

**Comment by arkenthera** [comment]
Fixed in 0e1d480
