### ISSUE TITLE
macOS Sierra. Test app don't actually vibrant

### ISSUE THREAD

**Issue by MaxGraey** [arkenthera/electron-vibrancy#10]
#### What actually I have:
![acreenshot](https://dl.dropboxusercontent.com/u/33221668/no-vibrancy.jpg)

So It seems very weak vibrancy

**Comment by oskarkrawczyk** [comment]
That **is** a vibrant window.

**Comment by MaxGraey** [comment]
Yes, it's my bad. I change Material to 9 and vibrancy making is more obvious)

**Comment by arkenthera** [comment]
Also play with the *alpha* value in the test app to see how it affects. The default is [0.4](https://github.com/arkenthera/electron-vibrancy/blob/master/spec/app/index.html#L13).

**Comment by arkenthera** [comment]
Also check out [this](https://github.com/sindresorhus/caprine/pull/136) by @oskarkrawczyk

**Comment by MaxGraey** [comment]
I have another problem:

Window with focus:

![vibrancy-focus](https://dl.dropboxusercontent.com/u/33221668/vibrancy-focus.jpg)

Window without focus is solid grey:

![vibrancy-blur](https://dl.dropboxusercontent.com/u/33221668/vibrancy-blur.jpg)

**Comment by oskarkrawczyk** [comment]
@MaxGraey This is the default behavior on macOS – every app using vibrancy does this. Even OS' native apps.

**Comment by MaxGraey** [comment]
@oskarkrawczyk I got it, thanks for response!

**Comment by vmarquet** [comment]
@oskarkrawczyk @MaxGraey I'm having the same problem than [this](https://github.com/arkenthera/electron-vibrancy/issues/10#issuecomment-259449289) (a solid grey background when window is not focused), could you please explain how to keep vibrant effect or point to relevant documentation?

**Comment by vmarquet** [comment]
Okay I just saw that vibrancy is now integrated into electron and that their implementation does not cause the grey background problem.

Never mind.
