### ISSUE TITLE
White background at corners

### ISSUE THREAD

**Issue by chuckhendo** [arkenthera/electron-vibrancy#11]
I'm noticing white backgrounds behind the corners if I have an element up against the edge of the window (such as with a titlebar). This is not occurring if I disable electron-vibrancy. This is in macOS Sierra using Electron v1.4.5. It seems to occur on both retina and non-retina displays.

![image](https://cloud.githubusercontent.com/assets/1184341/20178517/8b9faf76-a71f-11e6-898e-db38dd07137c.png)

**Comment by arkenthera** [comment]
Hey, can you take a loot at [caprine](https://github.com/sindresorhus/caprine/pull/136) ? There doesn't seem a white background on the screenshots posted there. Maybe try with a dark material ? And it would be better if you can replicate the issue on the test app so I can help further.

**Comment by chuckhendo** [comment]
Ok, Caprine doesn't have a problem. Neither does my app when I set the material to 9. However, I am able to demonstrate the problem on the test app:

https://github.com/chuckhendo/electron-vibrancy

**Comment by arkenthera** [comment]
Hey the PR for vibrancy in Electron has been merged to master. So I'd advise to wait for it to hit the release version and stop using this module.
