### ISSUE TITLE
Trouble getting started.

### ISSUE THREAD

**Issue by ghost** [arkenthera/electron-vibrancy#19]
Can someone please make a step by step on how to achieve the vibrancy effect on Windows 10? I am new to this and can't figure out where to get started.

**Comment by 0x61726b** [comment]
Hey, the instructions in [README](https://github.com/arkenthera/electron-vibrancy/blob/master/README.md) works. Though, the Electron version is hard-coded so if you have a dfiferent Electron version you need to recompile the module. 

After cloning the repo and `npm install`, run `electron --version` to see your version. Then to build the module type `node-gyp rebuild --target=1.7.1 --runtime=electron --arch=x64 --debug --dist-url=https://atom.io/download/atom-shell` where `1.7.1` should be the version you have (output of `electron --version`. After it is successfuly compiled just run `electron spec/app` and the test app will run.

**Comment by ghost** [comment]
This is where I am stuck. I don't know what's the problem, I have the latest node, npm, windows-build-tools, and Visual Studio 2017, I don't have any others programs opened.. ![feedback01](https://user-images.githubusercontent.com/3695322/34385010-61b08386-eb28-11e7-9c31-c7f5b7f8d475.JPG)

**Comment by ghost** [comment]
As you can all see, I managed to get it working, apparently I had a problem with permissions in %appdata%\Roaming\npm folder.. those were messed up and I couldn't install global npm modules there. ![feedback02](https://user-images.githubusercontent.com/3695322/34392824-4f9d80de-eb57-11e7-95ec-4339603d1850.JPG)

Aside from that, I wanted to know what happens if I build the app. I tried with electron-builder, on both x32 and x64, unpacked and with the nsis (Setup).. and lastly portable, but they all seem to give me the same error about some kind of binding.. does anyone know why, or am I doing something wrong and I am required to have some files near the executable?
![feedback03](https://user-images.githubusercontent.com/3695322/34392974-00159802-eb58-11e7-8537-7d89ecd0d81d.JPG)

**Comment by 0x61726b** [comment]
You need to use some kind of mechanism to build the native modules and put into the right place when you're packing the app. For example [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/wiki/Module-Structure----Two-package.json-Structure) has a similar system. The error you have says that it cant find the `Vibrancy.node` file inside the packaged app.

**Comment by ghost** [comment]
That's what I was thinking too, but I don't know where should I put the Vibrancy.node file.

**Comment by ghost** [comment]
After using the npm module of electron-vibrancy and setting it as a dependency, electron-builder seems to take care of the problem and package the app correctly. I'll close now the issue, if I encounter any problems, I'll come back. Thank you.
