### ISSUE TITLE
Launching devtools breaks rendering

### ISSUE THREAD

**Issue by oskarkrawczyk** [arkenthera/electron-vibrancy#2]
This is really weird and I can't really explain what's happening except for what stated in the title.

You'll also notice that for some reason when devtools is active the background becomes white. 

Attaching video of the behavior: https://v.usetapes.com/6MFjFXyx2Y

Env:

- Electron 1.4.2
- Sierra 10.12.1

**Comment by arkenthera** [comment]
I think dev tools in general breaks the transparency. But not every time. Create a normal non-vibrant window with transparency and set it full transparent. Then open the dev tools, transparency will *probably* break. I dont think it is strictly related to this module.

**Comment by arkenthera** [comment]
Transparency in Chromium is a tricky subject because it is directly related to the hardware. Can you open the dev tools with the detached flag to see if it breaks anything? On my PC, if I open the dev tools detached, rendering isnt broken.

```openDevTools({ detach: true });```

**Comment by oskarkrawczyk** [comment]
Curiously adding that flag completely removes vibrancy from the window.

<img width="864" alt="screen shot 2016-10-26 at 22 07 39" src="https://cloud.githubusercontent.com/assets/34213/19743190/a42802b2-9bc8-11e6-853f-477883e96b93.png">

**Comment by arkenthera** [comment]
Thats interesting. Can you try it in the test app of this repository? Just to verify this. Add ```mainWindow.openDevTools({ detach: true });``` to [here](https://github.com/arkenthera/electron-vibrancy/blob/master/test/main.js#L24), run ```npm test``` and see if the behaviour is the same.

**Comment by arkenthera** [comment]
Also I see your app has a frame. Did you see [here](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#limitations)?

**Comment by oskarkrawczyk** [comment]
> Also I see your app has a frame. Did you see here?

I did, but having these two keys with any values has zero effect on the app when vibrancy module is active. It always produces the same results (vibrancy + frame)

**Comment by oskarkrawczyk** [comment]
I'll have to look into this tomorrow and see why the test app seems to work fine even with dev tools attached – my apps config is essentially the same but as you can see, weird things are happening.

**Comment by arkenthera** [comment]
Can it be due to the fact that you're opening the dev tools just after creating the window? The test app opens it after the SetVibrancy call.

**Comment by oskarkrawczyk** [comment]
I'll do some digging tomorrow morning when my brain isn't fried after the whole day of coding ;-)

**Comment by oskarkrawczyk** [comment]
Looks like there's something weird with my app – can't really figure out. But I can live with vibrancy not working well in development. What's more pressing is #3 ;-)

**Comment by arkenthera** [comment]
> What's more pressing is #3 ;-)

I'll look into it very soon.
