### ISSUE TITLE
Windows 10 Fluent Design / Acrylic material

### ISSUE THREAD

**Issue by marcinciarka** [arkenthera/electron-vibrancy#21]
Fall Creators update gave us the acrylic material ability, can electron-vibrancy utilize this for WIndows?

**Comment by 0x61726b** [comment]
I think only UWP apps are able to use those new features. Unless I'm missing something that should be the case. I'll do some research anyway.

**Comment by 23phy** [comment]
Any news?

**Comment by 23phy** [comment]
Maybe with [windows.ui.xaml.media](https://www.npmjs.com/package/@nodert-win10-cu/windows.ui.xaml.media) from [NodeRT](https://github.com/NodeRT/NodeRT) it would be possible. That's where the [Acrylic API](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.acrylicbrush) is located.

**Comment by VatsaPatel** [comment]
Waiting for acrylic support too.

**Comment by 23phy** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/fbf70eb2-c012-465e-9c1e-7b092675dfd8-4ba7e302-d537-41bb-b84d-79cb2c0317f9-v1.png?transparent=1&palette=1&width=128) I did some research and it's definitely possible, the NodeRT gives you access to all the UWP APIs so you can use them in your Electron applications, but I am struggling with building the  [windows.ui.xaml.media](https://www.npmjs.com/package/@nodert-win10-cu/windows.ui.xaml.media) module.. looks like there are many errors which are beyond my comprehension. A log can be found below. I've used Visual Studio 2017 (successfully built other modules with it so it's not the VS, I tried with VS2015 but with the same results)
[build.log](https://github.com/arkenthera/electron-vibrancy/files/1758142/build.log) (If you open it I suggest you use VSCode or Sublime)

**Comment by 0x61726b** [comment]
I've found this quote on SO talking about AcrylicBrush;

> It's effects are created using the Lower level XAML Composition APIs, which uses UWP's XAML Compositor, so I would say that I doubt you will be able to achieve this natively in Win32. If you really want it, you can either take your app across the Desktop Bridge, and convert the UI, or mimic the effects with the technology available today. (Browsers such as Chrome, manage to use bring the Window Chrome further into their app, although I'm not sure how you would achieve the acrylic effect).

Even though the API might be usable, it is possible it will have no effect. Still, we will have to try and see if it will work or not.

**Comment by VatsaPatel** [comment]
Any new findings about the API ?

**Comment by 23phy** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/1d8e1e5a-3266-4bff-9013-da00167bdb5d-4ba7e302-d537-41bb-b84d-79cb2c0317f9-v1.png?transparent=1&palette=1&width=128)
Sadly, not really, but another way of using UWP APIs in your Node project (Electron in my case), is to have a background task that handles the UWP things, see [electron-uwp-background](https://github.com/felixrieseberg/electron-uwp-background), I am not yet sure if it is possible to have achieve Acrylic effect in your window with this solution but I am investigating, it is really late now, but I will try tomorrow, will keep you updated.

**Comment by 23phy** [comment]
Great news everyone, lately Windows started to roll out the new build called `Redstone 4` (Windows 10 version 1803), and exposed some new stuff about acrylic effects in Win32 apps. I modified `electron-vibrancy` a bit and I got the result I wanted but with a single problem, and it's that the background of the Electron app (with the acrylic effect) was of the size of your resolution, albeit your app which has a fixed width and height, I'll investigate this more in depth and after I figure out how to work with N-API, I'll build a module just for that effect on Windows, it'll be called [`electron-acrylic`](https://github.com/23phy/electron-acrylic). I'll keep you updated.

**Comment by 23phy** [comment]
The module is on [it's way](https://github.com/23phy/electron-acrylic), just a few bugs here and there. How's looking so far:
- The full window (I've used Snipping Tool)
![acrylic](https://user-images.githubusercontent.com/11774416/40028344-fc7ac59a-57e6-11e8-85b0-eb6a41a951ba.png)

- This is on desktop:
![screenshot 21](https://user-images.githubusercontent.com/11774416/40028362-0ca0091c-57e7-11e8-927d-d2aece880479.png)

- And [here](https://youtu.be/5vuXk7n0gzs) (YouTube) is moving :O

Gonna game a little and go to sleep, updates tomorrow, I hope to finish this week and release it to npm.

**Comment by matthiasg** [comment]
@23phy this is is this issue closed or still work in progress ? I really like what you did so far and would love to see it continued.

**Comment by 23phy** [comment]
The module that I am building is not related to this repo, just this specific issue (the UWP acrylic blur). If @arkenthera wants to merge the two repos, s/he is more than welcome. I tried to make a fork and adding to that one but I don't quite understand NAN. That's why I made another module for this issue with N-API. This issue can be closed indeed, but someone should leave a reference to the [`electron-acrylic`](https://github.com/23phy/electron-acrylic) module in case it will remain standalone.

**Comment by matthiasg** [comment]
@23phy thanks for the update .. will follow your work on acrylic over there then

**Comment by 23phy** [comment]
Cool, then @dreszczyk can close this issue.

**Comment by 0x61726b** [comment]
Good work @23phy!. Although, I recommend making this change for Electron rather than making a new module. Make a PR and it will most likely be supported and eventually merged,it will be easier for Electron developers to use it in their projects.

**Comment by wdanilo** [comment]
What happened to this topic @arkenthera and @23phy ? @23phy your work is spectacular. It seems you spend amazing amount of time to make it work. Why the last step did not happen? :( Is it possible to add it to electron?
