### ISSUE TITLE
`resize` event is not being fired

### ISSUE THREAD

**Issue by oskarkrawczyk** [arkenthera/electron-vibrancy#3]
Looks like the `resize` event on `window` is not being fired when activating vibrancy via this module.

Tested with a simple:

```js
window.addEventListener("resize", function(e){
  console.log(e.target.outerWidth)
})
```

Env:

- Electron 1.4.2
- Sierra 10.12.1

✏️ **Edit:**

Just to be clear, I've ran a test on the test app provided in this repo.

**Comment by arkenthera** [comment]
I've attempted a fix at 06cfaf1 on the [dev branch](https://github.com/arkenthera/electron-vibrancy/tree/dev). Can you try it out?

**Comment by oskarkrawczyk** [comment]
@arkenthera No joy, nothing inside of the `resize` listener gets triggered on resize – https://v.usetapes.com/CrptysTPrS

Also, this is probably just because it's dev (WIP), but the contents of `<body>` are not displayed.

**Comment by arkenthera** [comment]
Also, I've changed the API slightly in f90ec9c. Check out the README [here](https://github.com/arkenthera/electron-vibrancy/blob/dev/README.md)

**Comment by oskarkrawczyk** [comment]
@arkenthera the test app in your repo works? Is there anything I can provide as debug info?

**Comment by arkenthera** [comment]
I'm at f90ec9c on the dev branch at the moment and this is what I get.

http://i.imgur.com/aVOSv1O.gifv


index.html has

```
window.addEventListener("resize", function(e){
      console.log(e.target.outerWidth);
    });
```

**Comment by arkenthera** [comment]
Can you try running ```npm run rebuild``` ? Just to be sure.

**Comment by oskarkrawczyk** [comment]
Yes, that was it! I can confirm that the resize event works fine now. Thanks!

**Comment by arkenthera** [comment]
Nice! If you find anything else please report it again! I'll release the module on NPM tomorrow, hopefully without any bugs.

**Comment by oskarkrawczyk** [comment]
Awesome, I'll poke around today and see if I can integrate it into my [overcast-mac](https://github.com/oskarkrawczyk/overcast-mac) without issues

**Comment by oskarkrawczyk** [comment]
@arkenthera Just a followup, only happening in my app, not the test app.

I've noticed that when I disabled `mainWindow.webContents.openDevTools({ detach: true })` (comment out), `electron-vibrancy` will throw the following error:

<img width="471" alt="screen shot 2016-10-29 at 11 20 00" src="https://cloud.githubusercontent.com/assets/34213/19828568/d70b8ab6-9dc9-11e6-8b91-cf5a590a7313.png">

When Dev Tools are available, no error is thrown and the app launches correctly.

Do you have any idea what might be the cause of this?

**Comment by arkenthera** [comment]
I think I might know the reason,I changed the `SetVibrancy` function in the dev branch. It now accepts the `BrowserWindow` object rathen than the `getNativeWindowHandle()`. See [here](https://github.com/arkenthera/electron-vibrancy/blob/dev/README.md#setvibrancywindow-material-win--macos).Sorry about the confusion.

**Comment by oskarkrawczyk** [comment]
@arkenthera Unfortunately that wasn't it.

I don't want to be too annoying and I know it's asking a lot but perhaps you could have a look into this branch https://github.com/oskarkrawczyk/overcast-mac/tree/vibrancy, maybe it'll be something really obvious to you.

```
npm install https://github.com/arkenthera/electron-vibrancy.git#dev
npm start:dev # this will work
npm start # this will cause erorr
```

**Comment by arkenthera** [comment]
No way! I love trying to help to people use that something I made!

So I replaced [L#68](https://github.com/oskarkrawczyk/overcast-mac/blob/vibrancy/main.js#L68) to
`electronVibrancy.SetVibrancy(mainWindow,2)`  and both `npm start:dev` and `npm start` works without throwing any error. Is this not the case for you?

**Comment by oskarkrawczyk** [comment]
@arkenthera That worked, thank you! 👍
