### ISSUE TITLE
Awesome Electron List

### ISSUE THREAD

**Issue by knpwrs** [arkenthera/electron-vibrancy#4]
Now that there is a first release it might be worth considering submitting this to [sindresorhus/awesome-electron](https://github.com/sindresorhus/awesome-electron).

**Comment by arkenthera** [comment]
Sure thing! Though, it says in their [contributing.md](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md)
>If you just created something, wait at least 20 days before submitting.

and

>Submitted packages should be tested and documented.

Hmm,I'm not sure about how to test this module, maybe using [spectron](https://github.com/electron/spectron) and maybe some parameter validation tests.

**Comment by knpwrs** [comment]
I was looking at your initial commit, which is older than 20 days. Release date may be safer to go by.

I actually have a [ci branch](https://github.com/knpwrs/electron-vibrancy/tree/ci) which currently simply builds to make sure there aren't any silly compilation errors when there are changes. It looks like you've added travis in the meantime, I can submit a PR for Appveyor / Windows. As for tests, my only idea was to launch a process and make sure it doesn't crash. Validating anything beyond that sounds rather difficult.

**Comment by arkenthera** [comment]
Yeah I've just copy pasted the travis code from my other projects. To run an electron process in CI environment, dont we need to run it in headless mode since build machines have no graphics cards? I dont have much experience in testing with electron but I think we need to run it through `spectron` regardless. For Appveyor I'd be glad to have your PR!

**Comment by knpwrs** [comment]
I believe headless is fine, my initial concern was just making sure it doesn't crash. Anything less than crashing is probably just visual degradation but not critical to any real functionality. It would be nice to be able to test that everything is *working*, but I'm not sure how to get there at this time.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-electron/commit/d8ca6669e5377acd35a5d11fd28c0bdbba836a33 :)

**Comment by arkenthera** [comment]
Thanks @sindresorhus!

**Comment by sindresorhus** [comment]
@arkenthera fyi https://github.com/sindresorhus/caprine/pull/136

**Comment by arkenthera** [comment]
Oh wow, it looks so cool!
