### ISSUE TITLE
Unavailable to install by Node v7.0.0 - node-inspector dependency cannot be installed

### ISSUE THREAD

**Issue by MikeLP** [arkenthera/electron-vibrancy#6]
```
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp) 
...
```

Seems like node-inspector issue only. Btw latest commit was on 9 April. 
Is it possible to add this package as optional dependency? 

My temporary **solution**:

- rollback to Node v6.9.1
- install node-inspector dependency globally
- install electron-vibrancy

Anyway it's not working on Node v7.0.0 yet.

**Comment by arkenthera** [comment]
We actually don't need `node-inspector` for now so I've removed them in f237c11 on dev branch. Builds seem fine on both Travis and my machine. I can publish a new release. Does this look ok to you?

**Comment by arkenthera** [comment]
Just released `v0.1.1`. It should work on node `v7.0.0` now. Let me know if there is a problem

**Comment by MikeLP** [comment]
I've tested on both machines - macbook pro and desktop pc - here is new issue seems (old issue gone)

**Comment by arkenthera** [comment]
Travis build for macOS on node `v7.0.0` passes and on my Windows 10 too. Can you cd into 'electron-vibrancy` and  try running these in following order:

```
npm run conf
npm run rebuild
npm test
```

**Comment by MikeLP** [comment]
So I did it. It's works if you clone your project separately and will do  `npm install`  and / or
```
npm run conf
npm run rebuild
npm test
```
But I still get issue when I run like

`npm install electron-vibrance`

Let me try repeat and test this on my Windows 10. I will write here little bit later.

**Comment by arkenthera** [comment]
I see I actually didnt try on `electron-quick-start` yet.I think I know why it fails, I will look at it tomorrow. Sorry for the troubles.

**Comment by MikeLP** [comment]
First of all thank you very much for your work. I'm appreciate it. :)

About example of colored vibrance - please look airmail app
https://rink.hockeyapp.net/apps/84be85c3331ee1d222fd7f0b59e41b04
It's free for beta builds. Left sidebar looks like little different than default dark material view.

**Comment by arkenthera** [comment]
Hey, hopefully this is fixed now, can you verify?

**Comment by MikeLP** [comment]
Yep. Fixed. Thanks.

**Comment by kanish-111** [comment]
does this work on latest electron 14 build,  im getting this error

```
npm ERR! code 1                                                                                                                                                                 
npm ERR! path /usr/local/lib/node_modules/electron-vibrancy
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CXX(target) Release/obj.target/Vibrancy/src/Vibrancy.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.1.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.7.0 found at "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
npm ERR! (node:75753) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/electron-vibrancy/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/mac/Library/Caches/node-gyp/16.1.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mac/Library/Caches/node-gyp/16.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mac/Library/Caches/node-gyp/16.1.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/electron-vibrancy',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/Vibrancy.cc:25:
npm ERR! In file included from ../src/./Vibrancy.h:28:
npm ERR! In file included from ../src/./Common.h:41:
npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:503:1: error: expected unqualified-id
npm ERR! @class NSString, Protocol;
npm ERR! ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:505:9: error: unknown type name 'NSString'
npm ERR! typedef NSString * NSExceptionName NS_EXTENSIBLE_STRING_ENUM;
npm ERR!         ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:506:9: error: unknown type name 'NSString'
npm ERR! typedef NSString * NSRunLoopMode NS_EXTENSIBLE_STRING_ENUM;
npm ERR!         ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:508:19: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT NSString *NSStringFromSelector(SEL aSelector);
npm ERR!                   ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:509:44: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT SEL NSSelectorFromString(NSString *aSelectorName);
npm ERR!                                            ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:511:19: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT NSString *NSStringFromClass(Class aClass);
npm ERR!                   ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:512:53: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT Class _Nullable NSClassFromString(NSString *aClassName);
npm ERR!                                                     ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:514:19: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
npm ERR!                   ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:514:50: error: unknown type name 'Protocol'
npm ERR! FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
npm ERR!                                                  ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:515:19: error: unknown type name 'Protocol'
npm ERR! FOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
npm ERR!                   ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:515:61: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
npm ERR!                                                             ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:519:30: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;
npm ERR!                              ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:519:53: error: format argument not an NSString
npm ERR! FOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;
npm ERR!                              ~~~~~~~~~~~~~~~~       ^                  ~
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:98:49: note: expanded from macro 'NS_FORMAT_FUNCTION'
npm ERR!         #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))
npm ERR!                                                        ^                    ~
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:520:31: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;
npm ERR!                               ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:520:63: error: format argument not an NSString
npm ERR! FOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;
npm ERR!                               ~~~~~~~~~~~~~~~~                ^                  ~
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:98:49: note: expanded from macro 'NS_FORMAT_FUNCTION'
npm ERR!         #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))
npm ERR!                                                        ^                    ~
npm ERR! In file included from ../src/Vibrancy.cc:25:
npm ERR! In file included from ../src/./Vibrancy.h:28:
npm ERR! In file included from ../src/./Common.h:41:
npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:8:
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:9:1: error: expected unqualified-id
npm ERR! @class NSString;
npm ERR! ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:19:63: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT void NSSetZoneName(NSZone * _Nullable zone, NSString *name)NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
npm ERR!                                                               ^
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:20:19: error: unknown type name 'NSString'
npm ERR! FOUNDATION_EXPORT NSString *NSZoneName(NSZone * _Nullable zone) NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
npm ERR!                   ^
npm ERR! In file included from ../src/Vibrancy.cc:25:
npm ERR! In file included from ../src/./Vibrancy.h:28:
npm ERR! In file included from ../src/./Common.h:41:
npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: expected unqualified-id
npm ERR! @class NSInvocation, NSMethodSignature, NSCoder, NSString, NSEnumerator;
npm ERR! ^
npm ERR! fatal error: too many errors emitted, stopping now [-ferror-limit=]
npm ERR! 20 errors generated.
npm ERR! make: *** [Release/obj.target/Vibrancy/src/Vibrancy.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 17.7.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/electron-vibrancy
npm ERR! gyp ERR! node -v v16.1.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2021-09-16T07_37_34_745Z-debug.log
```

**Comment by FormalSnake** [comment]
> does this work on latest electron 14 build, im getting this error
> 
> ```
> npm ERR! code 1                                                                                                                                                                 
> npm ERR! path /usr/local/lib/node_modules/electron-vibrancy
> npm ERR! command failed
> npm ERR! command sh -c node-gyp rebuild
> npm ERR! CXX(target) Release/obj.target/Vibrancy/src/Vibrancy.o
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@7.1.2
> npm ERR! gyp info using node@16.1.0 | darwin | x64
> npm ERR! gyp info find Python using Python version 3.7.0 found at "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
> npm ERR! (node:75753) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
> npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
> npm ERR! gyp info spawn /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'make',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/electron-vibrancy/build/config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/Users/mac/Library/Caches/node-gyp/16.1.0/include/node/common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/mac/Library/Caches/node-gyp/16.1.0',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/mac/Library/Caches/node-gyp/16.1.0/<(target_arch)/node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/electron-vibrancy',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp info spawn make
> npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
> npm ERR! In file included from ../src/Vibrancy.cc:25:
> npm ERR! In file included from ../src/./Vibrancy.h:28:
> npm ERR! In file included from ../src/./Common.h:41:
> npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:503:1: error: expected unqualified-id
> npm ERR! @class NSString, Protocol;
> npm ERR! ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:505:9: error: unknown type name 'NSString'
> npm ERR! typedef NSString * NSExceptionName NS_EXTENSIBLE_STRING_ENUM;
> npm ERR!         ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:506:9: error: unknown type name 'NSString'
> npm ERR! typedef NSString * NSRunLoopMode NS_EXTENSIBLE_STRING_ENUM;
> npm ERR!         ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:508:19: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT NSString *NSStringFromSelector(SEL aSelector);
> npm ERR!                   ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:509:44: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT SEL NSSelectorFromString(NSString *aSelectorName);
> npm ERR!                                            ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:511:19: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT NSString *NSStringFromClass(Class aClass);
> npm ERR!                   ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:512:53: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT Class _Nullable NSClassFromString(NSString *aClassName);
> npm ERR!                                                     ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:514:19: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
> npm ERR!                   ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:514:50: error: unknown type name 'Protocol'
> npm ERR! FOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
> npm ERR!                                                  ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:515:19: error: unknown type name 'Protocol'
> npm ERR! FOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
> npm ERR!                   ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:515:61: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));
> npm ERR!                                                             ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:519:30: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;
> npm ERR!                              ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:519:53: error: format argument not an NSString
> npm ERR! FOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;
> npm ERR!                              ~~~~~~~~~~~~~~~~       ^                  ~
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:98:49: note: expanded from macro 'NS_FORMAT_FUNCTION'
> npm ERR!         #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))
> npm ERR!                                                        ^                    ~
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:520:31: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;
> npm ERR!                               ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:520:63: error: format argument not an NSString
> npm ERR! FOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;
> npm ERR!                               ~~~~~~~~~~~~~~~~                ^                  ~
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:98:49: note: expanded from macro 'NS_FORMAT_FUNCTION'
> npm ERR!         #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))
> npm ERR!                                                        ^                    ~
> npm ERR! In file included from ../src/Vibrancy.cc:25:
> npm ERR! In file included from ../src/./Vibrancy.h:28:
> npm ERR! In file included from ../src/./Common.h:41:
> npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
> npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
> npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:8:
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:9:1: error: expected unqualified-id
> npm ERR! @class NSString;
> npm ERR! ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:19:63: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT void NSSetZoneName(NSZone * _Nullable zone, NSString *name)NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
> npm ERR!                                                               ^
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSZone.h:20:19: error: unknown type name 'NSString'
> npm ERR! FOUNDATION_EXPORT NSString *NSZoneName(NSZone * _Nullable zone) NS_SWIFT_UNAVAILABLE("Zone-based memory management is unavailable");
> npm ERR!                   ^
> npm ERR! In file included from ../src/Vibrancy.cc:25:
> npm ERR! In file included from ../src/./Vibrancy.h:28:
> npm ERR! In file included from ../src/./Common.h:41:
> npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
> npm ERR! In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:5:
> npm ERR! /System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:10:1: error: expected unqualified-id
> npm ERR! @class NSInvocation, NSMethodSignature, NSCoder, NSString, NSEnumerator;
> npm ERR! ^
> npm ERR! fatal error: too many errors emitted, stopping now [-ferror-limit=]
> npm ERR! 20 errors generated.
> npm ERR! make: *** [Release/obj.target/Vibrancy/src/Vibrancy.o] Error 1
> npm ERR! gyp ERR! build error 
> npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
> npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> npm ERR! gyp ERR! System Darwin 17.7.0
> npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/electron-vibrancy
> npm ERR! gyp ERR! node -v v16.1.0
> npm ERR! gyp ERR! node-gyp -v v7.1.2
> npm ERR! gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/mac/.npm/_logs/2021-09-16T07_37_34_745Z-debug.log
> ```

exact same issue for me
