### ISSUE TITLE
Material Screenshots

### ISSUE THREAD

**Issue by knpwrs** [arkenthera/electron-vibrancy#7]
Here are materials `1` - `9` [as requested on Twitter](https://twitter.com/arkenthera/status/792435144644788225). Material `0` was the same as material `1` in my case.

![1](https://cloud.githubusercontent.com/assets/174864/19833319/bc7214f8-9e0b-11e6-8331-be49ca3eeab9.png)
![2](https://cloud.githubusercontent.com/assets/174864/19833322/bc7f168a-9e0b-11e6-9c84-c2a746538edc.png)
![3](https://cloud.githubusercontent.com/assets/174864/19833323/bc7fc5b2-9e0b-11e6-830c-90b9ba3f5a6e.png)
![4](https://cloud.githubusercontent.com/assets/174864/19833324/bc80c7c8-9e0b-11e6-8346-c619aa5db923.png)
![5](https://cloud.githubusercontent.com/assets/174864/19833325/bc81e23e-9e0b-11e6-95c1-d036bba40dc7.png)
![6](https://cloud.githubusercontent.com/assets/174864/19833320/bc7e1a28-9e0b-11e6-94e0-acddbf3f4689.png)
![7](https://cloud.githubusercontent.com/assets/174864/19833321/bc7e9bba-9e0b-11e6-9f76-840e46c38b38.png)
![8](https://cloud.githubusercontent.com/assets/174864/19833327/bc8b2c2c-9e0b-11e6-9272-8d84ad3b7116.png)
![9](https://cloud.githubusercontent.com/assets/174864/19833326/bc8a239a-9e0b-11e6-80f8-e5abd35a741f.png)

**Comment by arkenthera** [comment]
Wow thanks a lot! Can I use these in the README ?

**Comment by knpwrs** [comment]
Just so it's documented here as well, yes go ahead. :)
