### ISSUE TITLE
"This isnt supported on Electron"

### ISSUE THREAD

**Issue by 1j01** [arkenthera/electron-vibrancy#9]
I'm guessing you mean "Windows", or "Windows or Linux"

**Comment by arkenthera** [comment]
Sorry if I understand you wrong but I'm guessing you mean the opening line on the README. As far as I know,vibrancy isn't supported on Electron regardless of the platform.[#3002](https://github.com/electron/electron/issues/3002)

**Comment by 1j01** [comment]
Oh, sorry I misinterpreted that as "this module isn't supported on Electron" which would be silly...

**Comment by arkenthera** [comment]
Oh ,I should word it better to avoid further confusion!
